//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC4EGO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mecc
    {
        public int Id { get; set; }
        public System.DateTime datum { get; set; }
        public byte fordulo { get; set; }
        public string hazai { get; set; }
        public string vendeg { get; set; }
        public Nullable<int> nezoszam { get; set; }
    }
}
